name: discord_application_utils
description: Dart utilities for writing Discord Applications.
publish_to: none
version: 0.0.0-a1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.0

dependencies:
  json_utils:
    git: https://github.com/enspyrco/json_utils

dev_dependencies:
  enspyr_lints:
    git: https://github.com/enspyrco/enspyr_lints
  test: ^1.21.0