name: discord_application_utils
description: Dart utilities for writing Discord Applications.
version: 0.0.0-a1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.0

dependencies:
  json_utils: ^0.0.0-a1

dev_dependencies:
  enspyr_lints: ^0.0.0-a1
  test: ^1.21.0